export const opsData = {
  "kpis": {
    "deploymentReadiness": 76.1,
    "releaseRisk": 50.2,
    "labelingThroughput": 98.8,
    "blockedQuotes": 18,
    "highSeveritySignals": 72,
    "customerImpact": 3515938
  },
  "deploymentQueue": [
    {
      "deployment_id": "DEP002",
      "workflow": "maintenance intake",
      "stage": "discovery",
      "owner": "Product Engineering",
      "readiness_score": 74.2,
      "escalation_score": 102.3,
      "priority_score": 119.1,
      "high_severity_signals": 6,
      "customer_impact_usd": 241473,
      "recommended_action": "escalate field feedback into release planning"
    },
    {
      "deployment_id": "DEP003",
      "workflow": "exception management",
      "stage": "staging",
      "owner": "Product Engineering",
      "readiness_score": 66.8,
      "escalation_score": 88.4,
      "priority_score": 110.0,
      "high_severity_signals": 5,
      "customer_impact_usd": 193999,
      "recommended_action": "run readiness review with deployment and product engineering"
    },
    {
      "deployment_id": "DEP021",
      "workflow": "maintenance intake",
      "stage": "staging",
      "owner": "GTM Enablement",
      "readiness_score": 73.1,
      "escalation_score": 89.3,
      "priority_score": 106.7,
      "high_severity_signals": 5,
      "customer_impact_usd": 223918,
      "recommended_action": "run readiness review with deployment and product engineering"
    },
    {
      "deployment_id": "DEP027",
      "workflow": "vendor coordination",
      "stage": "pilot",
      "owner": "Product Ops",
      "readiness_score": 87.4,
      "escalation_score": 87.4,
      "priority_score": 95.6,
      "high_severity_signals": 5,
      "customer_impact_usd": 180420,
      "recommended_action": "escalate field feedback into release planning"
    },
    {
      "deployment_id": "DEP015",
      "workflow": "vendor coordination",
      "stage": "staging",
      "owner": "Deployment",
      "readiness_score": 78.0,
      "escalation_score": 79.7,
      "priority_score": 93.9,
      "high_severity_signals": 4,
      "customer_impact_usd": 270123,
      "recommended_action": "escalate field feedback into release planning"
    },
    {
      "deployment_id": "DEP012",
      "workflow": "collections follow-up",
      "stage": "production",
      "owner": "Product Ops",
      "readiness_score": 69.7,
      "escalation_score": 72.9,
      "priority_score": 92.5,
      "high_severity_signals": 4,
      "customer_impact_usd": 217490,
      "recommended_action": "run readiness review with deployment and product engineering"
    },
    {
      "deployment_id": "DEP014",
      "workflow": "vendor coordination",
      "stage": "pilot",
      "owner": "Deployment",
      "readiness_score": 74.5,
      "escalation_score": 74.7,
      "priority_score": 91.2,
      "high_severity_signals": 3,
      "customer_impact_usd": 201790,
      "recommended_action": "escalate field feedback into release planning"
    },
    {
      "deployment_id": "DEP020",
      "workflow": "delivery tracking",
      "stage": "pilot",
      "owner": "Product Engineering",
      "readiness_score": 80.6,
      "escalation_score": 74.4,
      "priority_score": 87.0,
      "high_severity_signals": 3,
      "customer_impact_usd": 125105,
      "recommended_action": "escalate field feedback into release planning"
    },
    {
      "deployment_id": "DEP024",
      "workflow": "collections follow-up",
      "stage": "staging",
      "owner": "Deployment",
      "readiness_score": 91.9,
      "escalation_score": 81.4,
      "priority_score": 86.7,
      "high_severity_signals": 4,
      "customer_impact_usd": 113092,
      "recommended_action": "escalate field feedback into release planning"
    },
    {
      "deployment_id": "DEP026",
      "workflow": "appointment scheduling",
      "stage": "expansion",
      "owner": "Product Engineering",
      "readiness_score": 73.3,
      "escalation_score": 67.9,
      "priority_score": 85.2,
      "high_severity_signals": 2,
      "customer_impact_usd": 121066,
      "recommended_action": "run readiness review with deployment and product engineering"
    }
  ],
  "releaseQueue": [
    {
      "feature_id": "FEAT011",
      "feature_name": "collections promise-to-pay verifier",
      "capability": "workflow tools",
      "release_phase": "general enablement",
      "owner": "Product Engineering",
      "docs_ready_pct": 52.5,
      "eval_pass_rate_pct": 81.9,
      "field_training_pct": 40.9,
      "deployments_blocked": 5,
      "blocked_deployment_ids": "DEP011;DEP007;DEP015;DEP025;DEP013",
      "gtm_motion": "new workflow",
      "price_packaging_status": "needs guardrails",
      "release_risk_score": 59.0
    },
    {
      "feature_id": "FEAT008",
      "feature_name": "agent memory conflict detector",
      "capability": "workflow tools",
      "release_phase": "general enablement",
      "owner": "Product Ops",
      "docs_ready_pct": 63.2,
      "eval_pass_rate_pct": 82.0,
      "field_training_pct": 41.6,
      "deployments_blocked": 5,
      "blocked_deployment_ids": "DEP013;DEP025;DEP019;DEP023;DEP001",
      "gtm_motion": "renewal defense",
      "price_packaging_status": "not priced",
      "release_risk_score": 55.8
    },
    {
      "feature_id": "FEAT007",
      "feature_name": "maintenance vendor routing",
      "capability": "reasoning",
      "release_phase": "design review",
      "owner": "Product Ops",
      "docs_ready_pct": 84.2,
      "eval_pass_rate_pct": 75.0,
      "field_training_pct": 57.5,
      "deployments_blocked": 6,
      "blocked_deployment_ids": "DEP003;DEP005;DEP027;DEP008;DEP013;DEP023",
      "gtm_motion": "pilot conversion",
      "price_packaging_status": "needs value metric",
      "release_risk_score": 51.4
    },
    {
      "feature_id": "FEAT001",
      "feature_name": "carrier check-call reason codes",
      "capability": "workflow tools",
      "release_phase": "general enablement",
      "owner": "Product Ops",
      "docs_ready_pct": 83.3,
      "eval_pass_rate_pct": 84.6,
      "field_training_pct": 49.1,
      "deployments_blocked": 5,
      "blocked_deployment_ids": "DEP022;DEP024;DEP006;DEP020;DEP019",
      "gtm_motion": "renewal defense",
      "price_packaging_status": "needs guardrails",
      "release_risk_score": 47.3
    },
    {
      "feature_id": "FEAT010",
      "feature_name": "operator console escalation queue",
      "capability": "workflow tools",
      "release_phase": "general enablement",
      "owner": "Product Ops",
      "docs_ready_pct": 46.6,
      "eval_pass_rate_pct": 78.1,
      "field_training_pct": 77.4,
      "deployments_blocked": 5,
      "blocked_deployment_ids": "DEP024;DEP006;DEP027;DEP015;DEP005",
      "gtm_motion": "new workflow",
      "price_packaging_status": "clear",
      "release_risk_score": 44.5
    },
    {
      "feature_id": "FEAT005",
      "feature_name": "webhook retry policy",
      "capability": "workflow tools",
      "release_phase": "staging",
      "owner": "GTM Enablement",
      "docs_ready_pct": 89.2,
      "eval_pass_rate_pct": 88.9,
      "field_training_pct": 64.9,
      "deployments_blocked": 6,
      "blocked_deployment_ids": "DEP008;DEP004;DEP015;DEP005;DEP026;DEP022",
      "gtm_motion": "pilot conversion",
      "price_packaging_status": "needs guardrails",
      "release_risk_score": 43.2
    },
    {
      "feature_id": "FEAT002",
      "feature_name": "multi-lingual voice fallback",
      "capability": "reasoning",
      "release_phase": "limited release",
      "owner": "Product Ops",
      "docs_ready_pct": 56.6,
      "eval_pass_rate_pct": 91.6,
      "field_training_pct": 73.2,
      "deployments_blocked": 4,
      "blocked_deployment_ids": "DEP015;DEP022;DEP007;DEP017",
      "gtm_motion": "renewal defense",
      "price_packaging_status": "not priced",
      "release_risk_score": 42.9
    },
    {
      "feature_id": "FEAT003",
      "feature_name": "staging eval regression suite",
      "capability": "voice",
      "release_phase": "limited release",
      "owner": "Deployment",
      "docs_ready_pct": 50.1,
      "eval_pass_rate_pct": 96.6,
      "field_training_pct": 51.6,
      "deployments_blocked": 4,
      "blocked_deployment_ids": "DEP008;DEP026;DEP007;DEP005",
      "gtm_motion": "pilot conversion",
      "price_packaging_status": "clear",
      "release_risk_score": 40.5
    }
  ],
  "labelingSummary": [
    {
      "capability": "coding",
      "items_labeled": 13631,
      "throughput_attainment_pct": 93.6,
      "qa_accept_rate_pct": 87.2,
      "consensus_rate_pct": 91.2,
      "rework_rate_pct": 14.8,
      "backlog_items": 11467,
      "labeling_risk_score": 27.0
    },
    {
      "capability": "reasoning",
      "items_labeled": 16665,
      "throughput_attainment_pct": 103.6,
      "qa_accept_rate_pct": 92.7,
      "consensus_rate_pct": 83.9,
      "rework_rate_pct": 10.6,
      "backlog_items": 11984,
      "labeling_risk_score": 20.1
    },
    {
      "capability": "voice",
      "items_labeled": 16431,
      "throughput_attainment_pct": 98.7,
      "qa_accept_rate_pct": 91.1,
      "consensus_rate_pct": 85.7,
      "rework_rate_pct": 11.6,
      "backlog_items": 9612,
      "labeling_risk_score": 18.9
    },
    {
      "capability": "workflow tools",
      "items_labeled": 14988,
      "throughput_attainment_pct": 99.2,
      "qa_accept_rate_pct": 91.6,
      "consensus_rate_pct": 85.1,
      "rework_rate_pct": 11.5,
      "backlog_items": 9740,
      "labeling_risk_score": 18.8
    }
  ],
  "gtmQueue": [
    {
      "package_id": "GTM05-INDUSTRIAL",
      "segment": "industrial services",
      "workflow": "maintenance intake",
      "pricing_model": "platform plus usage",
      "value_metric": "autonomous resolution",
      "sales_confidence_pct": 51.7,
      "technical_confidence_pct": 52.0,
      "missing_artifacts": "integration checklist",
      "quote_blocked": "yes",
      "enabled_reps": 23,
      "gtm_readiness_risk": 61.4
    },
    {
      "package_id": "GTM04-ENTERPRISE",
      "segment": "enterprise logistics",
      "workflow": "vendor coordination",
      "pricing_model": "platform plus usage",
      "value_metric": "cost per completed workflow",
      "sales_confidence_pct": 54.0,
      "technical_confidence_pct": 59.2,
      "missing_artifacts": "integration checklist",
      "quote_blocked": "yes",
      "enabled_reps": 14,
      "gtm_readiness_risk": 57.1
    },
    {
      "package_id": "GTM05-FIELD",
      "segment": "field operations",
      "workflow": "maintenance intake",
      "pricing_model": "per contact",
      "value_metric": "autonomous resolution",
      "sales_confidence_pct": 45.1,
      "technical_confidence_pct": 70.6,
      "missing_artifacts": "case study proof",
      "quote_blocked": "yes",
      "enabled_reps": 27,
      "gtm_readiness_risk": 55.6
    },
    {
      "package_id": "GTM01-FIELD",
      "segment": "field operations",
      "workflow": "appointment scheduling",
      "pricing_model": "pilot fee plus expansion",
      "value_metric": "manual hours removed",
      "sales_confidence_pct": 53.8,
      "technical_confidence_pct": 63.1,
      "missing_artifacts": "ROI calculator",
      "quote_blocked": "yes",
      "enabled_reps": 19,
      "gtm_readiness_risk": 55.4
    },
    {
      "package_id": "GTM04-INDUSTRIAL",
      "segment": "industrial services",
      "workflow": "vendor coordination",
      "pricing_model": "per resolved workflow",
      "value_metric": "cost per completed workflow",
      "sales_confidence_pct": 56.1,
      "technical_confidence_pct": 62.7,
      "missing_artifacts": "ROI calculator",
      "quote_blocked": "yes",
      "enabled_reps": 23,
      "gtm_readiness_risk": 54.6
    },
    {
      "package_id": "GTM02-FIELD",
      "segment": "field operations",
      "workflow": "delivery tracking",
      "pricing_model": "pilot fee plus expansion",
      "value_metric": "late delivery reduction",
      "sales_confidence_pct": 55.0,
      "technical_confidence_pct": 50.8,
      "missing_artifacts": "none",
      "quote_blocked": "yes",
      "enabled_reps": 7,
      "gtm_readiness_risk": 53.5
    },
    {
      "package_id": "GTM06-CUSTOMER",
      "segment": "customer operations",
      "workflow": "collections follow-up",
      "pricing_model": "platform plus usage",
      "value_metric": "autonomous resolution",
      "sales_confidence_pct": 47.5,
      "technical_confidence_pct": 73.2,
      "missing_artifacts": "ROI calculator",
      "quote_blocked": "yes",
      "enabled_reps": 4,
      "gtm_readiness_risk": 53.4
    },
    {
      "package_id": "GTM03-CUSTOMER",
      "segment": "customer operations",
      "workflow": "exception management",
      "pricing_model": "per contact",
      "value_metric": "late delivery reduction",
      "sales_confidence_pct": 48.9,
      "technical_confidence_pct": 60.9,
      "missing_artifacts": "none",
      "quote_blocked": "yes",
      "enabled_reps": 5,
      "gtm_readiness_risk": 51.4
    },
    {
      "package_id": "GTM06-FIELD",
      "segment": "field operations",
      "workflow": "collections follow-up",
      "pricing_model": "per contact",
      "value_metric": "late delivery reduction",
      "sales_confidence_pct": 42.2,
      "technical_confidence_pct": 84.7,
      "missing_artifacts": "integration checklist",
      "quote_blocked": "yes",
      "enabled_reps": 7,
      "gtm_readiness_risk": 50.3
    },
    {
      "package_id": "GTM03-INDUSTRIAL",
      "segment": "industrial services",
      "workflow": "exception management",
      "pricing_model": "pilot fee plus expansion",
      "value_metric": "late delivery reduction",
      "sales_confidence_pct": 54.0,
      "technical_confidence_pct": 74.7,
      "missing_artifacts": "case study proof",
      "quote_blocked": "yes",
      "enabled_reps": 12,
      "gtm_readiness_risk": 50.0
    }
  ],
  "feedbackLoop": [
    {
      "feedback_id": "FDBK0113",
      "event_date": "2026-03-22",
      "deployment_id": "DEP014",
      "channel": "Slack escalation",
      "signal_type": "customer escalation",
      "severity": "critical",
      "product_area": "orchestration",
      "customer_impact_usd": 89259,
      "time_to_triage_hours": 21.4,
      "status": "closed",
      "linked_feature_id": "FEAT004",
      "product_action": "train deployment team"
    },
    {
      "feedback_id": "FDBK0105",
      "event_date": "2026-04-04",
      "deployment_id": "DEP003",
      "channel": "QA review",
      "signal_type": "integration defect",
      "severity": "critical",
      "product_area": "orchestration",
      "customer_impact_usd": 86571,
      "time_to_triage_hours": 37.0,
      "status": "closed",
      "linked_feature_id": "FEAT003",
      "product_action": "escalate to product review"
    },
    {
      "feedback_id": "FDBK0202",
      "event_date": "2026-03-21",
      "deployment_id": "DEP015",
      "channel": "Slack escalation",
      "signal_type": "sales question",
      "severity": "critical",
      "product_area": "integrations",
      "customer_impact_usd": 84598,
      "time_to_triage_hours": 4.8,
      "status": "in progress",
      "linked_feature_id": "FEAT001",
      "product_action": "patch integration"
    },
    {
      "feedback_id": "FDBK0147",
      "event_date": "2026-04-09",
      "deployment_id": "DEP005",
      "channel": "QA review",
      "signal_type": "customer escalation",
      "severity": "critical",
      "product_area": "orchestration",
      "customer_impact_usd": 79845,
      "time_to_triage_hours": 13.4,
      "status": "triaged",
      "linked_feature_id": "FEAT009",
      "product_action": "escalate to product review"
    },
    {
      "feedback_id": "FDBK0124",
      "event_date": "2026-03-24",
      "deployment_id": "DEP013",
      "channel": "QA review",
      "signal_type": "sales question",
      "severity": "critical",
      "product_area": "operator console",
      "customer_impact_usd": 77800,
      "time_to_triage_hours": 20.9,
      "status": "triaged",
      "linked_feature_id": "FEAT006",
      "product_action": "patch integration"
    },
    {
      "feedback_id": "FDBK0100",
      "event_date": "2026-03-26",
      "deployment_id": "DEP009",
      "channel": "customer ops review",
      "signal_type": "eval failure",
      "severity": "critical",
      "product_area": "voice stack",
      "customer_impact_usd": 75930,
      "time_to_triage_hours": 11.7,
      "status": "in progress",
      "linked_feature_id": "FEAT004",
      "product_action": "escalate to product review"
    },
    {
      "feedback_id": "FDBK0210",
      "event_date": "2026-04-05",
      "deployment_id": "DEP001",
      "channel": "Slack escalation",
      "signal_type": "customer escalation",
      "severity": "critical",
      "product_area": "evals",
      "customer_impact_usd": 65947,
      "time_to_triage_hours": 40.1,
      "status": "new",
      "linked_feature_id": "FEAT006",
      "product_action": "write release note"
    },
    {
      "feedback_id": "FDBK0022",
      "event_date": "2026-04-13",
      "deployment_id": "DEP021",
      "channel": "field call",
      "signal_type": "sales question",
      "severity": "critical",
      "product_area": "orchestration",
      "customer_impact_usd": 63040,
      "time_to_triage_hours": 14.5,
      "status": "waiting on data",
      "linked_feature_id": "FEAT008",
      "product_action": "patch integration"
    },
    {
      "feedback_id": "FDBK0037",
      "event_date": "2026-03-31",
      "deployment_id": "DEP015",
      "channel": "QA review",
      "signal_type": "deployment blocker",
      "severity": "critical",
      "product_area": "orchestration",
      "customer_impact_usd": 58390,
      "time_to_triage_hours": 42.0,
      "status": "waiting on data",
      "linked_feature_id": "FEAT006",
      "product_action": "write release note"
    },
    {
      "feedback_id": "FDBK0083",
      "event_date": "2026-03-05",
      "deployment_id": "DEP017",
      "channel": "sales enablement",
      "signal_type": "customer escalation",
      "severity": "critical",
      "product_area": "integrations",
      "customer_impact_usd": 58384,
      "time_to_triage_hours": 23.7,
      "status": "new",
      "linked_feature_id": "FEAT007",
      "product_action": "escalate to product review"
    },
    {
      "feedback_id": "FDBK0235",
      "event_date": "2026-03-19",
      "deployment_id": "DEP012",
      "channel": "customer ops review",
      "signal_type": "customer escalation",
      "severity": "critical",
      "product_area": "voice stack",
      "customer_impact_usd": 57804,
      "time_to_triage_hours": 32.3,
      "status": "triaged",
      "linked_feature_id": "FEAT010",
      "product_action": "clarify pricing guardrail"
    },
    {
      "feedback_id": "FDBK0142",
      "event_date": "2026-04-20",
      "deployment_id": "DEP002",
      "channel": "Slack escalation",
      "signal_type": "sales question",
      "severity": "critical",
      "product_area": "evals",
      "customer_impact_usd": 53795,
      "time_to_triage_hours": 16.4,
      "status": "waiting on data",
      "linked_feature_id": "FEAT002",
      "product_action": "train deployment team"
    }
  ]
};
